In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("archive.zip")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [8]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [10]:
categorical_cols = ["gender", "Partner", "Dependents", "PhoneService", "MultipleLines", 
                    "InternetService", "OnlineSecurity", "DeviceProtection", "TechSupport", 
                    "StreamingTV", "StreamingMovies", "Contract", "PaperlessBilling", "PaymentMethod"]

# Apply One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [12]:
from sklearn.preprocessing import LabelEncoder

label_cols = ["Contract"]
le = LabelEncoder()

for col in label_cols:
    df[col] = le.fit_transform(df[col])  # Converts categories into numbers (e.g., 0, 1, 2)

In [14]:
binary_map = {"No": 0, "Yes": 1, "Female": 0, "Male": 1}
binary_cols = ["Partner", "Dependents", "PhoneService", "PaperlessBilling", "Churn", "gender"]

for col in binary_cols:
    df[col] = df[col].map(binary_map)

In [16]:
print(df.info())  # Check for any remaining object (categorical) columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   int64
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   int64
 4   Dependents        7043 non-null   int64
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   int64
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   int32
 16  PaperlessBilling  7043 non-null   int64
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   int64
dtypes: float64(1), int32(1), int64(8), object(11)
memory usage: 1.1+ MB
None

In [20]:
from sklearn.preprocessing import StandardScaler

# Identify numerical columns
numerical_cols = ["tenure", "MonthlyCharges", "TotalCharges"]

# Handle missing or empty values in TotalCharges (convert to numeric)
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")  # Convert to float
# Initialize StandardScaler
scaler = StandardScaler()

# Apply StandardScaler to numerical features
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

# Check scaled data
print(df.head())

   customerID  gender  SeniorCitizen  Partner  Dependents    tenure  \
0  7590-VHVEG       0              0        1           0 -1.277445
1  5575-GNVDE       1              0        0           0  0.066327
2  3668-QPYBK       1              0        0           0 -1.236724
3  7795-CFOCW       1              0        0           0  0.514251
4  9237-HQITU       0              0        0           0 -1.236724

   PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0             0  No phone service             DSL             No  ...
1             1                No             DSL            Yes  ...
2             1                No             DSL            Yes  ...
3             0  No phone service             DSL            Yes  ...
4             1                No     Fiber optic             No  ...

  DeviceProtection TechSupport StreamingTV StreamingMovies Contract  \
0               No          No          No              No        0
1              Yes          No          No              No        1
2               No          No          No              No        0
3              Yes         Yes          No              No        1
4               No          No          No              No        0

   PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 1           Electronic check      -1.160323     -0.994194
1                 0               Mailed check      -0.259629     -0.173740
2                 1               Mailed check      -0.362660     -0.959649
3                 0  Bank transfer (automatic)      -0.746535     -0.195248
4                 1           Electronic check       0.197365     -0.940457

   Churn
0      0
1      0
2      1
3      0
4      1

[5 rows x 21 columns]

In [68]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [72]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier, GradientBoostingClassifier, RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score



df.drop(columns=['customerID'], errors='ignore', inplace=True)  
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce').fillna(0)

X = df.drop(columns=['Churn'])  
y = df['Churn']

y = LabelEncoder().fit_transform(y)

categorical_cols = X.select_dtypes(include=['object']).columns
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

models = {
    "Bagging": BaggingClassifier(estimator=RandomForestClassifier(n_estimators=10), n_estimators=10, random_state=42),
    "AdaBoost": AdaBoostClassifier(n_estimators=20, random_state=42),
    "GradientBoosting": GradientBoostingClassifier(n_estimators=50, learning_rate=0.1, random_state=42),
    "XGBoost": XGBClassifier(n_estimators=20, random_state=42, eval_metric="logloss")
}

results = {}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    predictions = model.predict(X_test_scaled)
    results[name] = accuracy_score(y_test, predictions)
    print(f"{name} Accuracy: {results[name]:.4f}")

Bagging Accuracy: 0.7991

C:\Users\sania\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

AdaBoost Accuracy: 0.8105
GradientBoosting Accuracy: 0.8098
XGBoost Accuracy: 0.7999